### ISSUE TITLE
BellmanFord problems

### ISSUE THREAD

**Issue by soniakeys** [soniakeys/graph#43]
Doc says "Negative cycles are only detected when reachable from start.  A negative cycle not reachable from start will not prevent the algorithm from finding shortest paths reachable from start."  That an awful lot of "reachable from starts"

Also, can cycles actually be identified and returned easily?

**Comment by soniakeys** [comment]
Patched up quite a bit.  Doesn't do cycle enumeration, but does return a representative cycle.

**Comment by yxxin1984** [comment]
How can use this to detect negative cycles? Is there some example?

**Comment by soniakeys** [comment]
Hello yxx,

It seems Bellman Ford might not be best for enumerating all negative cycles.  I just did a quick search and found a candidate algorithm though, in the paper "Finding all the negative cycles in a directed graph" by lTakeo Yamada and Harunobu Kinoshita.  I added it to my issue #3.

**Comment by soniakeys** [comment]
NegativeCycles implemented, although poorly.  It could be more efficient, mutating a single G(F,R) rather than recreating it over and over.  Also it just implements the simple lower bound from the paper, not the improved lower bound.

**Comment by soniakeys** [comment]
And now NegativeCycles improved, avoiding graph copies and implementing the more sophisticated lower bound from the paper.
