### ISSUE TITLE
syntax error in sssp.go

### ISSUE THREAD

**Issue by john0312** [soniakeys/graph#49]
The file sssp.go in the current HEAD fails to build with the following error:
`graph/sssp.go:475: syntax error: unexpected range, expecting {`
`graph/sssp.go:519: non-declaration statement outside function body`
`graph/sssp.go:520: non-declaration statement outside function body`
`graph/sssp.go:521: syntax error: unexpected }`

To reproduce, install a fresh copy of Ubuntu 14.04, and install go and git ( `apt-get install golang git` ), then set GOPATH to an empty directory, then run:
`go get github.com/soniakeys/graph`

The version of go used is go1.2.1 linux/amd64.

I'm reporting this because this breaks prasmussen/gdrive.

Thank you.

**Comment by soniakeys** [comment]
Fixed,  and 1.2.1 target added to CI.

**Comment by soniakeys** [comment]
1.2 support abandoned.  gdrive is vendoring now, and its documented to require go 1.5 anyway.
