### ISSUE TITLE
Return all negative cycles starting from specific node

### ISSUE THREAD

**Issue by maxgillett** [soniakeys/graph#78]
Is there a simple adjustment to the [NegativeCycles](https://github.com/soniakeys/graph/blob/master/dir.go#L488) algorithm, or a composition of existing functions that can achieve this? I haven't had the time yet to go through the implementation in detail.

**Comment by soniakeys** [comment]
Added to #3.  The suggestion to use code from NegativeCycles seems reasonable.  The techniques of Yamada and Kinoshita should apply.

**Comment by soniakeys** [comment]
Added to #3. The suggestion to use code from NegativeCycles seems reasonable. The techniques of Yamada and Kinoshita should apply.
